# Utiliza uma imagem base leve do NGINX
FROM nginx:alpine

# Remove a configuração padrão do NGINX
RUN rm /etc/nginx/conf.d/default.conf

# Copia o arquivo de configuração personalizado do NGINX para o local correto no contêiner
# Este arquivo (nginx.conf) é essencial para que o roteamento de Single-Page Applications (SPA) funcione.
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia todos os arquivos da aplicação (HTML, TSX, etc.) para o diretório web do NGINX
COPY . /usr/share/nginx/html

# Expõe a porta 80 para permitir o tráfego para o NGINX dentro do contêiner
EXPOSE 80

# Comando para iniciar o NGINX em modo "foreground" quando o contêiner for executado
CMD ["nginx", "-g", "daemon off;"]